<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<Platforms>x64</Platforms>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<SelfContained>true</SelfContained>
		<PublishSingleFile>false</PublishSingleFile>
		<PublishReadyToRun>true</PublishReadyToRun>
		<ApplicationIcon>..\AndroidSyncControl\Resources\appicon.ico</ApplicationIcon>

		<Product>AndroidSyncControl.Updater</Product>
		<Company>AndroidSyncControl</Company>
		<Description>Production Update Engine for AndroidSyncControl</Description>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<Optimize>true</Optimize>
		<DebugType>none</DebugType>
		<DebugSymbols>false</DebugSymbols>
	</PropertyGroup>

</Project>
